# -*- coding: utf-8 -*-
"""BMI Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19qJMGoV4RrlW833E-ezrLk46Cau8ksWP
"""

name=input("enter your name:  ")
Weight=float(input("enter your weight in Kg: "))
Height=float(input("enter your Height in m : "))
BMI=Weight/(Height/100)**2
print(BMI)

if BMI>0:
    if(BMI<18.5):
      print(name+ ", you are underweight")
    elif(BMI<=24.9):
      print(name+ ", you are normal weight")
    elif(BMI<29.9):
      print(name+ ", you are overweight")
    elif(BMI<34.9):
      print(name+ ", you are obese")
    elif(BMI<39.9):
      print(name+ ", you are  severly obese")
    else:
      print(name+ ", you are morbidly obese.")